version: '3.8'

services:
  vastaanotolle-frontend:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    container_name: vastaanotolle-frontend
    restart: always
  vastaanotolle-backend:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
      args:
        POSTGRES_URL: ${POSTGRES_URL}
    container_name: vastaanotolle-backend
    environment:
      - POSTGRES_URL=${POSTGRES_URL}
      - PORT=${PORT}
    restart: always
    depends_on:
      - vastaanotolle-db
  vastaanotolle-db:
    image: postgres:13-alpine
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - vastaanotolle-frontend
      - vastaanotolle-backend

volumes:
  postgres-data:
  caddy_data:
  caddy_config:
