version: '3.8'

services:
  vastaanotolle_db:
    image: postgres
    environment:
      POSTGRES_DB: vastaanotolle_pg
      POSTGRES_USER: dev_admin
      POSTGRES_PASSWORD: dev_admin_password
    volumes:
      - vastaanotolle_pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  vastaanotolle_pg_data:
    driver: local