import React from 'react'
import ReactDOM from 'react-dom/client'
import './index.css'
import { createBrowserRouter, RouterProvider } from 'react-router-dom'
import Admin from './routes/Admin'

const router = createBrowserRouter([
  {
    path: '/',
    element: <div>To be implemented...</div>,
  },
  {
    path: '/admin',
    element: <Admin />,
  },
])

// biome-ignore lint/style/noNonNullAssertion: Autogenerated by Vite
ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <RouterProvider router={router} />
  </React.StrictMode>,
)
